import type { ConceptId } from "./core-v1";

export interface TaxonomyAliasRecord {
  alias: string;
  conceptId: ConceptId;
}

export const TAXONOMY_ALIASES_V1: TaxonomyAliasRecord[] = [
  { alias: "general", conceptId: "jc:docs:general" },
  { alias: "misc", conceptId: "jc:docs:general" },
  { alias: "uncategorized", conceptId: "jc:docs:general" },
  { alias: "other", conceptId: "jc:docs:general" },

  { alias: "programming", conceptId: "jc:docs:programming" },
  { alias: "software", conceptId: "jc:docs:programming" },
  { alias: "coding", conceptId: "jc:docs:programming" },
  { alias: "development", conceptId: "jc:docs:programming" },
  { alias: "engineering", conceptId: "jc:docs:programming" },
  { alias: "computer-science", conceptId: "jc:docs:programming" },
  { alias: "distributed-systems", conceptId: "jc:docs:programming:systems" },
  { alias: "databases", conceptId: "jc:docs:programming:systems" },
  { alias: "networking", conceptId: "jc:docs:programming:systems" },
  { alias: "rust", conceptId: "jc:docs:programming:languages" },
  { alias: "typescript", conceptId: "jc:docs:programming:languages" },
  { alias: "language-design", conceptId: "jc:docs:programming:languages" },
  { alias: "compilers", conceptId: "jc:docs:programming:languages" },
  { alias: "patterns", conceptId: "jc:docs:programming:architecture" },
  { alias: "ddd", conceptId: "jc:docs:programming:architecture" },
  { alias: "clean-architecture", conceptId: "jc:docs:programming:architecture" },
  { alias: "hexagonal", conceptId: "jc:docs:programming:architecture" },

  { alias: "business", conceptId: "jc:docs:business" },
  { alias: "finance", conceptId: "jc:docs:business" },
  { alias: "sales", conceptId: "jc:docs:business" },
  { alias: "entrepreneurship", conceptId: "jc:docs:business" },
  { alias: "creator-economy", conceptId: "jc:docs:business:creator" },
  { alias: "indie-business", conceptId: "jc:docs:business:creator" },
  { alias: "audience-building", conceptId: "jc:docs:business:creator" },
  { alias: "bootstrapped", conceptId: "jc:docs:business:creator" },

  { alias: "education", conceptId: "jc:docs:education" },
  { alias: "learning", conceptId: "jc:docs:education" },
  { alias: "teaching", conceptId: "jc:docs:education" },
  { alias: "curriculum", conceptId: "jc:docs:education" },
  { alias: "training", conceptId: "jc:docs:education" },
  { alias: "cognitive-science", conceptId: "jc:docs:education:learning-science" },
  { alias: "learning-theory", conceptId: "jc:docs:education:learning-science" },
  { alias: "memory", conceptId: "jc:docs:education:learning-science" },
  { alias: "cognitive-load", conceptId: "jc:docs:education:learning-science" },
  { alias: "instructional-design", conceptId: "jc:docs:education:pedagogy" },
  { alias: "ubd", conceptId: "jc:docs:education:pedagogy" },
  { alias: "curriculum-design", conceptId: "jc:docs:education:pedagogy" },

  { alias: "design", conceptId: "jc:docs:design" },
  { alias: "ux", conceptId: "jc:docs:design" },
  { alias: "ui", conceptId: "jc:docs:design" },
  { alias: "product-design", conceptId: "jc:docs:design" },
  { alias: "visual-design", conceptId: "jc:docs:design" },
  { alias: "game-design", conceptId: "jc:docs:design:game" },
  { alias: "game-feel", conceptId: "jc:docs:design:game" },
  { alias: "play", conceptId: "jc:docs:design:game" },
  { alias: "interactivity", conceptId: "jc:docs:design:game" },
  { alias: "systems-thinking", conceptId: "jc:docs:design:systems" },
  { alias: "complexity", conceptId: "jc:docs:design:systems" },
  { alias: "emergence", conceptId: "jc:docs:design:systems" },
  { alias: "product-design", conceptId: "jc:docs:design:product" },
  { alias: "ux", conceptId: "jc:docs:design:product" },
  { alias: "interaction-design", conceptId: "jc:docs:design:product" },

  { alias: "marketing", conceptId: "jc:docs:marketing" },
  { alias: "growth", conceptId: "jc:docs:marketing" },
  { alias: "brand", conceptId: "jc:docs:marketing" },
  { alias: "copywriting", conceptId: "jc:docs:marketing" },
  { alias: "positioning", conceptId: "jc:docs:marketing" },

  { alias: "strategy", conceptId: "jc:docs:strategy" },
  { alias: "planning", conceptId: "jc:docs:strategy" },
  { alias: "roadmap", conceptId: "jc:docs:strategy" },
  { alias: "go-to-market", conceptId: "jc:docs:strategy" },

  { alias: "ai", conceptId: "jc:docs:ai" },
  { alias: "machine-learning", conceptId: "jc:docs:ai" },
  { alias: "llm", conceptId: "jc:docs:ai" },
  { alias: "agents", conceptId: "jc:docs:ai" },
  { alias: "artificial-intelligence", conceptId: "jc:docs:ai" },
  { alias: "autonomous-agents", conceptId: "jc:docs:ai:agents" },
  { alias: "tool-use", conceptId: "jc:docs:ai:agents" },
  { alias: "agent-planning", conceptId: "jc:docs:ai:agents" },
  { alias: "multi-agent", conceptId: "jc:docs:ai:agents" },
  { alias: "rag", conceptId: "jc:docs:ai:applied" },
  { alias: "embeddings", conceptId: "jc:docs:ai:applied" },
  { alias: "vector-search", conceptId: "jc:docs:ai:applied" },
  { alias: "production-ai", conceptId: "jc:docs:ai:applied" },

  { alias: "operations", conceptId: "jc:docs:operations" },
  { alias: "ops", conceptId: "jc:docs:operations" },
  { alias: "runbook", conceptId: "jc:docs:operations" },
  { alias: "incident", conceptId: "jc:docs:operations" },
  { alias: "platform", conceptId: "jc:docs:operations" },

  { alias: "podcast", conceptId: "jc:docs:podcast" },
  { alias: "audio", conceptId: "jc:docs:podcast" },
  { alias: "episode", conceptId: "jc:docs:podcast" },
  { alias: "show", conceptId: "jc:docs:podcast" },
];
