apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  mountOptions:
    - nfsvers=3
    - tcp
    - resvport
  nfs:
    server: three-body
    path: /volume1/joelclaw
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: joelclaw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Ti
  volumeName: minio-nfs-pv
