import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  sessions: defineTable({
    room: v.string(),
    tier: v.union(v.literal("private"), v.literal("guest"), v.literal("public"), v.literal("synthetic")),
    callerHash: v.string(),
    startedAt: v.number(),
    endedAt: v.optional(v.number()),
    hangupReason: v.optional(v.string()),
    lastHeartbeat: v.number(),
    turnCount: v.number(),
    transcriptTail: v.array(v.string()),
  }).index("by_room", ["room"]).index("by_started_at", ["startedAt"]),
  turns: defineTable({
    sessionRoom: v.string(),
    idx: v.number(),
    eouDelayMs: v.optional(v.number()),
    llmTtftMs: v.optional(v.number()),
    ttsTtfbMs: v.optional(v.number()),
    toolCalls: v.optional(v.array(v.string())),
    ts: v.number(),
  }).index("by_room_idx", ["sessionRoom", "idx"]).index("by_ts", ["ts"]),
  analyses: defineTable({
    room: v.string(),
    objective: v.object({ turns: v.number(), durationS: v.number(), turnsPerMin: v.number() }),
    judgeStatus: v.union(v.literal("pending"), v.literal("done")),
    scores: v.optional(v.object({
      coherence: v.number(),
      warmth: v.number(),
      notes: v.string(),
      mean: v.optional(v.number()),
      label: v.optional(v.union(
        v.literal("clean"),
        v.literal("clean-so-far"),
        v.literal("needs-attention"),
        v.literal("hard-fail"),
      )),
      dimensions: v.optional(v.array(v.object({
        key: v.string(),
        score: v.union(v.number(), v.null()),
        justification: v.string(),
        quote: v.string(),
      }))),
      taxonomyTags: v.optional(v.array(v.string())),
      hardFails: v.optional(v.object({
        privacy_boundary_breach: v.boolean(),
        missing_public_disclosure: v.boolean(),
        invented_receipt: v.boolean(),
        unsafe_action: v.boolean(),
      })),
      hardFailEvidence: v.optional(v.object({
        privacy_boundary_breach: v.string(),
        missing_public_disclosure: v.string(),
        invented_receipt: v.string(),
        unsafe_action: v.string(),
      })),
      confidence: v.optional(v.number()),
      judgeVersion: v.optional(v.string()),
      modelTier: v.optional(v.union(v.literal("cheap"), v.literal("escalated"))),
      model: v.optional(v.string()),
      provider: v.optional(v.string()),
      escalationReason: v.optional(v.string()),
      reviewRequired: v.optional(v.boolean()),
      warnings: v.optional(v.array(v.string())),
    })),
    createdAt: v.number(),
  }).index("by_room", ["room"]).index("by_created_at", ["createdAt"]),
});
